variables:
  buildConfiguration: 'Release'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: buildCloud
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DotNetCoreCLI@2
      displayName: Dotnet restore
      inputs:
        command: restore
        projects: '**/*.csproj'
        includeNuGetOrg: true

    - task: DotNetCoreCLI@2
      displayName: Build Common
      inputs:
        command: build
        projects: '**/*.Common.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Build Cloud
      inputs:
        command: build
        projects: '**/*.Cloud.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Build Cloud Tests
      inputs:
        command: build
        projects: '**/*.Cloud.Tests.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Run Cloud unit tests - $(buildConfiguration)'
      inputs:
        command: 'test'
        arguments: '--no-build --configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '**/*.Cloud.Tests.csproj'

  - job: buildMobile
    pool:
      vmImage: 'macos-latest'
    variables: 
      outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**/*.sln'

    - task: XamarinAndroid@1
      inputs:
        projectFile: '**/*droid*.csproj'
        outputDirectory: '$(outputDirectory)'
        configuration: '$(buildConfiguration)'